### PR TITLE
Rename class methods

### PR DESCRIPTION
**Pull request by MarkWieczorek**
This pull request renames several class methods. To summarize, all methods are listed below, and those that were changed are in bold (with the old name after the colon).

The only two method names that I am not happy with are `SHWindow.return_coeffs` and `SHWindow.return_grid`, which return a new class SHCoeffs and SHGrid instance of a single localization window. These might not be necessary given the `to_array` and `to_grid` methods that return numpy arrays of the coefficients and grids.

In addition, I have added the operator `__pow__` to the list of operators that act on SHCoeffs, and I have added the optional arguement `check` to the method `convert` that checks if the function is real when converting complex coefficients to real coefficients. 

Do not merge before `fix-powerspectrum` and `oca`.

## SHCoeffs
* from_array()
* from_random()
* from_zeros()
* from_file()
* **to_file()** : tofile()
* **to_array()** : get_coeffs()
* **degrees()** : get_degrees()
* powerspectrum()
* set_coeffs()
* rotate()
* **convert()** : return_coeffs()
* **make_complex() -> incorporated into convert()**
* **make_real() -> incorporated into convert()**
* copy()
* plot_powerspectrum()
* plot_power()
* expand()
* info()

## SHGrid
* from_array()
* from_file()
* **to_file()** : tofile()
* **to_grid()** : get_grid()
* **lats()** : get_lats()
* **lons()** : get_lons()
* expand()
* copy()
* **plot()** : plot_rawdata()
* **plot3d()** : plot_3dsphere
* info()

## SHWindow
* from_cap()
* from_mask()
* **to_array()** : get_coeffs()
* **to_grid()** : get_grid()
* return_coeffs()
* return_grid()
* **number()** : get_k()
* **degrees()** : get_degrees()
* powerspectra()
* rotate()
* **couplingmatrix()** : get_couplingmatrix()
* **biasedpowerspectrum()** : get_biasedpowerspectrum()
* **multitaperpowerspectrum()** : get_multitaperpowerspectrum()
* **multitapercrosspowerspectrum()** : get_multitapercrosspowerspectrum()
* copy()
* plot_windows()
* plot_powerspectra()
* plot_couplingmatrix()
* info()

### CODE REVIEW

**Comment by ioshchepkov** [comment]
Nice changes! :)

1. I agree with your concerns about  `SHWindow.return_coeffs` and `SHWindow.return_grid`, but again I think it is better to use these methods (maybe renamed) instead of `to_array` and `to_grid`, because you always can use a chain `SHWindow.return_coeffs().to_array()` and **avoid repeating** not only in this class, but in library in general.

2. For my eyes `multitapercrosspowerspectrum` and other similar names are unreadable, I think `multitaper_cross_power_spectrum` is longer but better for readability.

**Comment by MMesch** [comment]
> For my eyes multitapercrosspowerspectrum and other similar names are unreadable, I think multitaper_cross_power_spectrum is longer but better for readability.

agree

**Comment by MMesch** [comment]
my proposal:

## SHCoeffs
* from_array()
* from_random()
* from_zeros()
* from_file()
* **to_file()** : tofile()
* **to_array()** : get_coeffs()
* **degrees()** : get_degrees()
* **get_spectrum()**: get_powerspectrum()
* set_coeffs()
* rotate()
* **convert()** : return_coeffs()
* **make_complex() -> incorporated into convert()**
* **make_real() -> incorporated into convert()**
* copy()
* **plot_spectrum()**: plot_powerspectrum()
* plot_power() -> remove ??
* expand()
* info()

## SHGrid
* from_array()
* from_file()
* **to_file()** : tofile()
* **to_grid()** : get_grid()
* **lats()** : get_lats()
* **lons()** : get_lons()
* expand()
* copy()
* **plot()** : plot_rawdata()
* **plot3d()** : plot_3dsphere
* info()

## SHWindow
* from_cap()
* from_mask()
* **to_array()** : get_coeffs()
* **to_grid()** : get_grid()
* return_coeffs()
* return_grid()
* **number()** : get_k()
* **degrees()** : get_degrees()
* **get_spectra()**: powerspectra()
* rotate()
* **get_coupling_matrix()** : get_couplingmatrix()
* **get_biased_spectrum()** : get_biasedpowerspectrum()
* **get_multitaper_spectrum()** : get_multitaperpowerspectrum()
* **get_multitaper_cross_spectrum()** : get_multitapercrosspowerspectrum()
* copy()
* plot_windows()
* plot_powerspectra()
* plot_couplingmatrix()
* info()

**Comment by MarkWieczorek** [comment]
Here is my renewed proposal, following gitter discussion

* `get_` is removed.
* underscores placed between all words.
* `powerspectrum()` replaced by `spectrum()` with optional argument `convention` equal to either `power` or `energy`.
* `plot_power()` renamed to `plot_coeffs(convention='power' or 'energy')`
* rename `SHWindow.return_coeffs()` to `SHWindow.to_SHCoeffs()` and `SHWindow.return_grid()` to `SHWindow.to_SHGrid()`.
* rename `SHWindow.number()` to `SHWindow.number_concentrated()`.

## SHCoeffs
* from_array()
* from_random()
* from_zeros()
* from_file()
* to_file()
* to_array()
* degrees()
* spectrum(), with optional argument `convention`=`power` or `energy`
* set_coeffs()
* rotate()
* convert()
* copy()
* plot_spectrum(), with optional argument `convention`=`power` or `energy`
* plot_coeffs(), with optional argument `convention`=`power` or `energy`
* expand()
* info()

## SHGrid
* from_array()
* from_file()
* to_file()
* to_grid()
* lats()
* lons()
* expand()
* copy()
* plot()
* plot3d()
* info()

## SHWindow
* from_cap()
* from_mask()
* to_array()
* to_grid()
* to_SHCoeffs()
* to_SHGrid()
* number_concentrated()
* degrees()
* spectra(), with optional argument `convention`=`power` or `energy`
* rotate()
* coupling_matrix()
* biased_spectrum(), with optional argument `convention`=`power` or `energy`
* multitaper_spectrum(), with optional argument `convention`=`power` or `energy`
* multitaper_cross_spectrum(), with optional argument `convention`=`power` or `energy`
* copy()
* plot_windows()
* plot_spectra(), with optional argument `convention`=`power` or `energy`
* plot_coupling_matrix()
* info()

**Pull request merged**
