### PR TITLE
Pypi fixes

### PR DESCRIPTION
**Pull request by MMesch**
This PR makes SHTOOLS pypi ready. It works on the testpypi server and can be installed with:

``` pip install -i https://testpypi.python.org/pypi pyshtools```

The version string needs to be improved because the direct git version fails for the pypi upload ...

### CODE REVIEW

**Comment by MMesch** [comment]
this shouldn't get merged immediately because it doesn't use the github version string

**Comment by MMesch** [comment]
To repeat the stuff from gitter: we just need to cleanly tag the final version, such that we can use the get_version() function. The download link needs to be adjusted as well, than it should work immediately on pypi.

**Comment by MarkWieczorek** [comment]
Do you want me to merge this with develop? The only issue I see is that this edit needs to be reverted to the url for master
~~~~
download_url='https://github.com/MMesch/SHTOOLS/zipball/pypi-fixes',
~~~~

**Comment by MMesch** [comment]
It can be merged now. I changed the dl-link

**Pull request merged**
