### PR TITLE
Break circular imports. #401

### PR DESCRIPTION
**Pull request by EricAtORS**
This breaks the circular import reported in #401 

**Reminders**

- [x] Base all changes on the `develop` branch: the `master` branch is used only when releasing new versions.
- [x] Run `make check` to ensure that the python code follows standard formatting conventions.
- [x] If adding new features, update the docstring to provide all information that is required to use the feature.

### CODE REVIEW

**Comment by MarkWieczorek** [comment]
Thanks for this. I don't understand why this works everywhere else, but if if solves your problem, great!

I'm not sure why the CI builds are failing. I suspect it has something to do with mamba (its certainly not your change...)

**Comment by EricAtORS** [comment]
@MarkWieczorek Thanks for merging it in so quickly.
Is there anything that I can do to help push that time line up? Mostly just looking for that bug fix.

**Comment by MarkWieczorek** [comment]
I need to go through the big PR about our upcoming transition to using the Meson build system, as this might be incorporated in the next release if it all works. I also would like to track down the bug that is crashing the CI tests (see https://github.com/SHTOOLS/SHTOOLS/actions/runs/5813995031/job/15777794561). If you know anything about either of those, that would help.

Putting out new releases is always a pain: half the time it goes smoothly, the other half I need to spend a lot of time updating build procedure. The windows builds are the most problematic, though the last two times they were pretty easy. I just need to find a week where I have the time to invest in this in case something goes wrong. The best time would probably be the end of august...

**Comment by EricAtORS** [comment]
Perfect.

For the build issue,
I'm not familiar with github actions, but it's definitely something I'm looking in to learning.

But I've always seen similar issues when there's a desync between mamba and conda. Either mamba needs to be updated or conda needs to be held back if mamba hasn't updated with the newest change.

I'll see what I can do with this.

For windows, feel free to tag me.
I was also the one who pushed the changes on conda-forge.
I was also trying to package it up in conan for our internal use, but managing fortran on windows was not that straight forward... so I can feel your pain.

**Pull request merged**
