### PR TITLE
Add C wrapper for MakeGradientDH

### PR DESCRIPTION
**Pull request by eschnett**
**Reminders**

- [x] Base all changes on the `develop` branch: the `master` branch is used only when releasing new versions.
- [x] Run `make check` to ensure that the python code follows standard formatting conventions.
- [x] If adding new features, update the docstring to provide all information that is required to use the feature.

Closes https://github.com/SHTOOLS/SHTOOLS/issues/289.

### CODE REVIEW

**Comment by eschnett** [comment]
The C API I designed assumes that the two output arrays `theta` and `phi` have the same shape. If that's not desirable, I can update it to allow different shapes.

**Comment by MarkWieczorek** [comment]
Sorry for the delay. I'll try to look at this by the end of the week.

**Comment by MarkWieczorek** [comment]
@eschnett This looks good to me. But could you rebase your PR off the `develop` branch? As soon as this is done, I'll merge your changes. Thanks!

**Comment by eschnett** [comment]
Rebased.

**Comment by MarkWieczorek** [comment]
It still says that you are trying to merge this into master....

**Comment by eschnett** [comment]
I think I'll have to open a new pull request.

**Pull request closed without merging**
